#!/bin/sh

pgrep -x picom > /dev/null ||		picom -b &
pgrep -x sxhkd > /dev/null || 		sxhkd &
pgrep polkit-gnome > /dev/null || 	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
					setxkbmap -layout eu &	# keyboard layout
pgrep -x polybar > /dev/null || 	polybar -r kawa &
pgrep -x udiskie > /dev/null || 	udiskie &
pgrep -x redshift > /dev/null || 	redshift &
					~/.fehbg & # wallpaper
					wal -R &
pgrep -x light-locker > /dev/null || 	light-locker &
pgrep -x ulauncher > /dev/null ||	ulauncher --no-window &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        3
bspc config window_gap          16

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Ulauncher border=off


# fix cursor theme when outside of windows
xsetroot -cursor_name left_ptr

# pywal colors
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bash /home/konrad/.config/bspwm/bspwm_colors.sh &
